%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) (equal for both cameras after stereo rectification)
Camera.fx: 260.4708254827622
Camera.fy: 261.839672846784
Camera.cx: 311.4989497955604
Camera.cy: 183.83828311365187

Camera.k1: -0.04047286101733648
Camera.k2: 0.03290399844880891
Camera.p1: -3.639089000347129e-05
Camera.p2: -7.543482846769623e-05

Camera.width: 640
Camera.height: 360

# Camera frames per second
Camera.fps: 15.0

# stereo baseline times fx
Camera.bf: 30.7824

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40.0 # 35

# Transformation from camera 0 to body-frame (imu)
Tbc: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [ 0.01266748786793992, -0.9999195854532419, -0.0005978111189532953, 0.021043392437225177,
          -0.002444290718898623, 0.000566891800383662, -0.99999685203333, -0.005615005674174008,
          0.999916776633935, 0.012668909215280022, -0.002436913067364599, -0.026426172666751298,
          0.0, 0.0, 0.0, 1.0 ]

# IMU noise
# get it from Project of **zed-examples/tutorials/tutorial 7 - sensor data/**.
IMU.NoiseGyro: 8.6e-05 # 1.6968e-04
IMU.NoiseAcc: 0.0014 # 2.0000e-3
IMU.GyroWalk: 2.2e-06
IMU.AccWalk: 8.0e-05 # 3.0000e-3
IMU.Frequency: 200

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 360
LEFT.width: 640
LEFT.D: !!opencv-matrix
  rows: 1
  cols: 5
  dt: d
  data: [ -0.04047286101733648, 0.03290399844880891, -3.639089000347129e-05, -7.543482846769623e-05 ]
LEFT.K: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ 260.4708254827622, 0.0, 311.4989497955604, 0.0, 261.839672846784, 183.83828311365187, 0.0, 0.0, 1.0 ]
LEFT.R: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0 ]
LEFT.Rf: !!opencv-matrix
  rows: 3
  cols: 3
  dt: f
  data: [ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0 ]
LEFT.P: !!opencv-matrix
  rows: 3
  cols: 4
  dt: d
  data: [ 260.4708254827622, 0.0, 311.4989497955604, 0.0, 0.0, 261.839672846784, 183.83828311365187, 0.0, 0.0, 0.0, 1.0, 0.0 ]

RIGHT.height: 360
RIGHT.width: 640
RIGHT.D: !!opencv-matrix
  rows: 1
  cols: 5
  dt: d
  data: [ -0.02949275721766671, 0.02160932560841085, 0.0016769349691857051, -0.0011984007286533849 ]
RIGHT.K: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ 259.8971704001385, 0.0, 312.24425384714283, 0.0, 261.2575486475671, 184.1229328586056, 0.0, 0.0, 1.0 ]
RIGHT.R: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0 ]
RIGHT.P: !!opencv-matrix
  rows: 3
  cols: 4
  dt: d
  data: [  259.8971704001385, 0.0, 312.24425384714283, 0.0, 0.0, 261.2575486475671, 184.1229328586056, 0.0, 0.0, 0.0, 1.0, 0.0 ]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2200

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize:2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

