imu0:
  T_i_b:
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.0014
  accelerometer_random_walk: 8.0e-05
  gyroscope_noise_density: 8.6e-05
  gyroscope_random_walk: 2.2e-06
  model: calibrated
  rostopic: /zed2/zed_node/imu/data_raw
  time_offset: 0.0
  update_rate: 200.0
